import os

os.system('pip install pip -U')
os.system('pip install wheel -U')
os.system('pip install aiohttp -U')

os.system('pip install asyncio')
os.system('pip install progressbar')
os.system('pip install time')
os.system('pip install tkinter')
os.system('pip install tkinter.ttk')
os.system('pip install random')
os.system('pip install typing')
os.system('pip install flask')
os.system('pip install requests')
os.system('pip install threading')
os.system('pip install PIL')
os.system('pip install sys')
os.system('pip install pyttsx3')
os.system('pip install gtts')
os.system('pip install tqdm')
os.system('pip install pynput')
os.system('pip install pyglet')
os.system('pip install youtube_dl')
os.system('pip install platform')

os.system('pip install asyncio -U')
os.system('pip install progressbar -U')
os.system('pip install time -U')
os.system('pip install tkinter -U')
os.system('pip install tkinter.ttk -U')
os.system('pip install random -U')
os.system('pip install typing -U')
os.system('pip install flask -U')
os.system('pip install requests -U')
os.system('pip install threading -U')
os.system('pip install PIL -U')
os.system('pip install sys -U')
os.system('pip install pyttsx3 -U')
os.system('pip install gtts -U')
os.system('pip install tqdm -U')
os.system('pip install pynput -U')
os.system('pip install pyglet -U')
os.system('pip install youtube_dl -U')
os.system('pip install platform -U')

print(f'   ')
print(f'   ')
print(f'   ')
print(f'   ')
print(f'   ')
print(f'   ')
print(f'   ')
print(f'   ')
print(f'   ')
print(f'   ')
print(f'   ')
print(f'   ')
print(f'   ')
print(f'   ')
print(f'   ')
print(f'   ')
print(f'   ')
print(f'   ')
print(f'   ')
print(f'   ')
print(f'   ')
print(f'   ')
print(f'   ')
print(f'   ')
print(f'   ')
print(f'   ')
print(f'   ')
print(f'   ')
print(f'   ')
print(f'   ')
print(f'   ')
print(f'   ')
print(f'   ')
print(f'   ')
print(f'   ')
print(f'   ')
print(f'   ')
print(f'   ')
print(f'   ')
print(f'   ')
print(f'   ')
print(f'   ')
print(f'   ')
print(f'   ')
print(f'   ')
print(f'   ')
print(f'   ')
print(f'   ')
print(f'   ')
print(f'   ')
print(f'   ')
print(f'   ')
print(f'   ')
print(f'   ')
print(f'   ')
print(f'   ')
print(f'   ')
print(f'   ')
print(f'   ')
print(f'   ')
print(f'   ')
print(f'   ')
print(f'   ')
print(f'   ')
print(f'   ')
print(f'   ')
print(f'   ')
print(f'   ')
print(f'   ')
print(f'   ')
print(f'   ')
print(f'   ')
print(f'   ')
print(f'   ')
print(f'   ')
print(f'   ')
print(f'   ')
print(f'   ')
print(f'   ')
print(f'   ')
print(f'   ')
print(f'   ')
print(f'   ')
print(f'   ')
print(f'   ')
print(f'   ')
print(f'   ')
print(f'   ')
print(f'   ')
print(f'   ')
print(f'   ')
print(f'   ')
print(f'   ')
print(f'   ')
print(f'   ')
print(f'   ')
print(f'   ')
print(f'   ')
print(f'   ')
print(f'   ')
print(f'   ')
print(f'   ')
print(f'   ')
print(f'   ')
print(f'   ')
print(f'   ')
print(f'   ')
print(f'   ')
print(f'   ')
print(f'   ')
print(f'   ')
print(f'   ')
print(f'   ')
print(f'   ')
print(f'   ')
print(f'   ')
print(f'   ')
print(f'   ')
print(f'   ')
print(f'   ')
print(f'   ')
print(f'   ')
print(f'   ')
print(f'   ')
print(f'   ')
print(f'   ')
print(f'   ')
print(f'   ')
print(f'   ')
print(f'   ')
print(f'   ')
print(f'   ')
print(f'   ')
print(f'   ')
print(f'   ')
print(f'   ')
print(f'   ')
print(f'   ')
print(f'   ')
print(f'   ')
print(f'   ')
print(f'   ')
print(f'   ')
print(f'   ')
print(f'   ')
print(f'   ')
print(f'   ')
print(f'   ')
print(f'   ')
print(f'   ')
print(f'   ')
print(f'   ')
print(f'   ')
print(f'   ')
print(f'   ')
print(f'   ')
print(f'   ')
print(f'   ')
print(f'   ')
print(f'   ')
print(f'   ')
print(f'   ')
print(f'   ')
print(f'   ')
print(f'   ')
print(f'   ')
print(f'   ')
print(f'   ')
print(f'   ')
print(f'   ')
print(f'   ')
print(f'   ')
print(f'   ')
print(f'   ')
print(f'   ')
print(f'   ')
print(f'   ')
print(f'   ')
print(f'   ')
print(f'   ')
print(f'   ')
print(f'   ')
print(f'   ')
print(f'   ')
print(f'   ')
print(f'   ')
print(f'   ')
print(f'   ')
print(f'   ')
print(f'   ')
print(f'   ')
print(f'   ')
print(f'   ')
print(f'   ')
print(f'   ')
print(f'   ')
print(f'   ')
print(f'   ')
print(f'   ')
print(f'   ')
print(f'   ')
print(f'   ')
print(f'   ')
print(f'   ')
print(f'   ')
print(f'   ')
print(f'   ')
print(f'   ')
print(f'   ')
print(f'   ')
print(f'   ')
print(f'   ')
print(f'   ')
print(f'   ')
print(f'   ')
print(f'   ')
print(f'   ')
print(f'   ')
print(f'   ')
print(f'   ')
print(f'   ')
print(f'   ')
print(f'   ')
print(f'   ')
print(f'   ')
print(f'   ')
print(f'   ')
print(f'   ')
print(f'   ')
print(f'   ')
print(f'   ')
print(f'   ')
print(f'   ')
print(f'   ')
print(f'   ')
print(f'   ')
print(f'   ')
print(f'   ')
print(f'   ')
print(f'   ')
print(f'   ')
print(f'   ')
print(f'   ')
print(f'   ')
print(f'   ')
print(f'   ')
print(f'   ')
print(f'   ')
print(f'   ')
print(f'   ')
print(f'   ')
print(f'   ')
print(f'   ')
print(f'   ')
print(f'   ')
print(f'   ')
print(f'   ')
print(f'   ')
input(f'Библиотеки были обновлены и установлены')